### ISSUE TITLE
module 'cv2.cv2' has no attribute 'xfeatures2d'

### ISSUE THREAD

**Issue by adhilartz** [linrl3/image_stitching#2]
python Image_Stitching.py [image1.jpg] [image2.jpg]
Traceback (most recent call last):
  File "Image_Stitching.py", line 78, in <module>
    main(sys.argv[1],sys.argv[2])
  File "Image_Stitching.py", line 74, in main
    final=Image_Stitching().blending(img1,img2)
  File "Image_Stitching.py", line 9, in __init__
    self.sift=cv2.xfeatures2d.SIFT_create()
AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'

**Comment by A7med01** [comment]
SIFT is a patented algorithm, hence not available in each open-cv version.
try
`!pip install opencv-contrib-python`

**Comment by Egorka** [comment]
Hi @adhilartz 

try to replace:

`self.sift=cv2.xfeatures2d.SIFT_create()`

to

`self.sift=cv2.SIFT_create()`

in latest versions of opencv-python SIFT migrated in core from xfeatures2d
