### ISSUE TITLE
UnboundLocalError: local variable 'H' referenced before assignment

### ISSUE THREAD

**Issue by monkeycc** [linrl3/image_stitching#6]
```
Traceback (most recent call last):
  File "d:\Image-Stitching-OpenCV\Image_Stitching.py", line 92, in <module>
    main(imageA,imageB)
  File "d:\Image-Stitching-OpenCV\Image_Stitching.py", line 74, in main
    final=Image_Stitching().blending(imageA,imageB)
  File "d:\Image-Stitching-OpenCV\Image_Stitching.py", line 51, in blending
    H = self.registration(img1,img2)
  File "d:\Image-Stitching-OpenCV\Image_Stitching.py", line 31, in registration
    return H
UnboundLocalError: local variable 'H' referenced before assignment
```

**Comment by Narukara** [comment]
应该是因为不满足上面的 `len(good_points) > min_match`，匹配上的点不够多
